package com.iredko.testBook;

/**
 * Created by IRedko on 21.09.2017.
 */
public enum Watercolors {ZINC, LEMON, YELLOW, MEDIUM_YELLOW, DEEP_YELLOW, ORANGE, BRILLIANT_RED, CRIMSON, MAGENTA,
    ROSE_MADDER,VIOLET, CERULEAN_BLUE_HUE, PHTHALO_BLUE,ULTRAMARINE, COBALT_BLUE_HUE,PERMANENT_GREEN, VIRIDIAN_HUE,
    SAP_GREEN, YELLOW_OCHRE, BURNT_SIENNA, RAW_UMBER, BURNT_UMBER,PAYNES_GRAY, IVORY_BLACK}
